#!/usr/bin/env bash
#displays numbers from 1 to 100
#Displays Fizz Buzz when number is multiple of 3 and 5
#Diplays Buzz when the numbers is a multiple of 5
#otherwise displays the number
i=1

until [ $i -gt 100 ]
do
	if [[ $(( i % 5 )) -eq 0 && $(( i % 3 )) -eq 0 ]]
	then
		echo FizBuzz
	elif [ $(( i % 3 )) -eq 0 ]
	then
		echo Fizz
	elif [ $(( i % 5 )) -eq 0 ]
	then
		echo Buzz
	else
		echo $i
	fi
	i=$(( i + 1 ))
done
