#!/usr/bin/env bash
#Display the contents of the file /etc/passwd
# prpint only the username, usrId an user home direcotry

myfile="/etc/passwd"
while read -r line
do
	echo "$line" | cut -d":" -f1,3,6
done < "$myfile"
