#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#display good luck for the 8th loop iteration
#displays Best School for other iterations
i=1
while [ $i -lt 11 ]
do
	if [ $i -eq 4 ]
	then
		echo bad luck
	elif [ $i -eq 8 ]
	then
		echo good luck
	else
		echo Best School
	fi
	i=$((i + 1))
done
