#!/usr/bin/env bash
#Display number for 1 to 20
#display 4 then bad luck from china for the 4th loop iteration
#display 9 and then bad luck from Japan for the 9th loop iteration
#display 17 then bad luck from italy for the 17th loop iteration
i=1
while [ $i -lt 21 ]
do
	echo $i
	case $i in
		4)
		echo bad luck from China
		;;
		9)
		echo bad luck from Japan
		;;
		17)
		echo bad luck from Italy
		;;
	esac
	i=$((i + 1))	
done
